org: sertton
app: serverless-app
service: serverless-shipping

plugins:
  - serverless-offline

stages:
  prod:
    observability: true 

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 10
  tracing:
    lambda: true
  environment:
    DOMAIN: ${env:DOMAIN}
    ORIGIN_ZIPCODE: ${env:ORIGIN_ZIPCODE}
    MELHOR_ENVIO_CLIENT_ID: ${env:MELHOR_ENVIO_CLIENT_ID}
    MELHOR_ENVIO_SECRET: ${env:MELHOR_ENVIO_SECRET}
    MELHOR_ENVIO_URL: ${env:MELHOR_ENVIO_URL}
    MELHOR_ENVIO_API_URL: ${env:MELHOR_ENVIO_API_URL}
    REDIS_URL: ${env:REDIS_URL}

functions:
  authorize:
    handler: ./src/app/aws/functions/auth/authorize.handler
    events:
      - http:
          path: /api/auth/authorize
          method: GET
          cors: true

  callback:
    handler: ./src/app/aws/functions/auth/callback.handler
    events:
      - http:
          path: /api/auth/callback
          method: GET
          cors: true

  calculate-quotes:
    handler: ./src/app/aws/functions/shipping/calculate-quotes.handler
    events:
      - http:
          path: /api/shipping/quotes
          method: POST
          cors: true
